name: 'gh-release-with-wf-dispatch'
description: 'release'
author: 'dionomusuko'
branding:
  icon: 'fast-forward'
  color: 'green'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/dionomusuko/gh-release-with-wf-dispatch@sha256:28843375f8f4b1fcc84f082a2b48b5baa985bee09202a8f1f77c853fc70a0711'
inputs:
  github_token:
    description: 'GitHub personal access token'
    required: true
    default: ${{ github.token }}
  release_file_path:
    description: 'release file path'
    required: true
  repo_full_name:
    description: 'repository full name'
    required: true
    default: ${{ github.repository }}
  base_branch:
    description: 'base branch'
    required: true
    default: 'main'
  user_name:
    description: 'git config user.name'
    required: false
    default: 'github-actions[bot]'
  user_email:
    description: 'git config user.email'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  next_semver_level:
    description: 'semver level to bump'
    required: true
  assignees:
    description: 'comma separated assignees for pull-request'
    required: false
    default: ${{ github.actor }}
