name: 'gh-release-with-wf-dispatch'
description: 'release'
author: 'dionomusuko'
branding:
  icon: 'fast-forward'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  github_token:
    description: 'github token'
    required: true
    default: ${{ github.token }}
  release_file_path:
    description: 'release file path'
    required: true
  owner:
    description: 'owner'
    required: true
  repo:
    description: 'repository'
    required: true
  repo_full_name:
    description: 'repository full name'
    required: true
  base_branch:
    description: 'base branch'
    required: true
    default: 'master'
  new_tag:
    description: 'new release tag, if you are doing patch-version-release, there is no need to configure'
    required: false
