name: Release

on:
  workflow_dispatch:
    inputs:
      release_file_path:
        description: "path to RELEASE file"
        required: true
        type: choice
        options:
          - RELEASE
          - testdata/RELEASE
      next_semver_level:
        description: "semver level to bump"
        required: true
        type: choice
        options:
          - patch
          - minor
          #- major

jobs:
  main:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # https://github.com/actions/checkout/releases/tag/v3.1.0
      - uses: dionomusuko/gh-release-with-wf-dispatch@main
        with:
          github_token: ${{ secrets.GH_PAT }}
          release_file_path: ${{ github.event.inputs.release_file_path }}
          next_semver_level: ${{ github.event.inputs.next_semver_level }}
